apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: recorder-go-zero
  name: recorder-go-zero
  namespace: k8sotel
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recorder-go-zero
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-go: "opentelemetry-operator-system/elastic-instrumentation"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/recorder-zero"
      labels:
        io.kompose.service: recorder-go-zero
    spec:
      containers:
        - env:
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: admin
          image: us-central1-docker.pkg.dev/elastic-sa/tbekiares/recorder-go-zero:latest
          name: recorder-go-zero
          ports:
            - containerPort: 9003
              protocol: TCP
      restartPolicy: Always
