threads:
  - name: proxy
    schedule:
      - type: nginx
        backfill_start_minutes: 720
        backfill_stop_minutes: 360
        logs_per_second: 1000
        name: proxy
      - type: request_errors
        browser: chrome
        region: APAC
      - type: nginx
        backfill_start_minutes: 360
        backfill_stop_minutes: 0
        logs_per_second: 1000
        name: proxy
      - type: nginx
        backfill_start_minutes: 0
        logs_per_second: 1000
        name: proxy
  - name: trader
    schedule:
      - type: trader
        backfill_start_minutes: 720
        backfill_stop_minutes: 0
        logs_per_second: 100
        name: trader
      - type: trader
        backfill_start_minutes: 0
        logs_per_second: 100
        name: trader