apiVersion: apps/v1
kind: Deployment
metadata:
  name: monkey
  namespace: k8sotel
  labels:
    io.kompose.service: monkey
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: monkey
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "opentelemetry-operator-system/elastic-instrumentation"
      labels:
        io.kompose.service: monkey
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/elastic-sa/tbekiares/monkey:latest
          name: monkey
          ports:
            - containerPort: 9002
              protocol: TCP
      restartPolicy: Always
