apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: notifier
  name: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notifier
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: notifier
    spec:
      containers:
        - image: notifier:latest
          imagePullPolicy: Never
          name: notifier
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
