apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postgresql
  name: postgresql
  namespace: k8sotel
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql
  template:
    metadata:
      labels:
        io.kompose.service: postgresql
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: trades
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: admin
          image: postgres:latest
          name: postgresql
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
