apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: processor
  name: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: processor
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: processor
    spec:
      containers:
        - env:
            - name: BOOTSTRAP_SERVER
              value: kafka:9093
            - name: IN_GROUP
              value: processor
            - name: IN_TOPIC
              value: notifications_q
          image: processor:latest
          imagePullPolicy: Never
          name: processor
      restartPolicy: Always
