apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: recorder-go-zero
  name: recorder-go-zero
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recorder-go-zero
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: recorder-go-zero
    spec:
      containers:
        - env:
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: admin
          image: recorder-go-zero:latest
          imagePullPolicy: Never
          name: recorder-go-zero
          ports:
            - containerPort: 9003
              protocol: TCP
      restartPolicy: Always
