apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: elastic-instrumentation
spec:
  java:
    image: docker.elastic.co/observability/elastic-otel-javaagent:1.3.0
    extensions:
      - image: us-central1-docker.pkg.dev/elastic-sa/tbekiares/baggage-processor:$COURSE
        dir: /extensions
    env:
      - name: OTEL_JAVA_TEST_SPAN_ATTRIBUTES_COPY_FROM_BAGGAGE_INCLUDE
        value: '*'
      - name: OTEL_JAVA_TEST_LOG_ATTRIBUTES_COPY_FROM_BAGGAGE_INCLUDE
        value: '*'
      - name: OTEL_LOGS_EXPORTER
        value: 'experimental-otlp/stdout'
      - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_LOG_ATTRIBUTES
        value: 'true'
      - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_KEY_VALUE_PAIR_ATTRIBUTES
        value: 'true'
      - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MDC_ATTRIBUTES
        value: '*'
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "com.example.log.format=otlpjson"
