#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

cd $WORKSPACE_DIR
patch -i /workspace/src/trader/patch/add_attribute.diff /workspace/src/trader/app.py
patch -i /workspace/src/trader/patch/remove_blrp.diff /workspace/src/trader/app.py
docker compose up -d --build

exit 0
