dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/k8sobserver $CORE_VERSION
  - gomod: go.opentelemetry.io/collector/extension/memorylimiterextension $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension $CORE_VERSION

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/httpcheckreceiver $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sobjectsreceiver $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/nginxreceiver $CORE_VERSION
  - gomod: go.opentelemetry.io/collector/receiver/nopreceiver $CORE_VERSION
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/receivercreator $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver $CORE_VERSION

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter $CORE_VERSION
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter $CORE_VERSION
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter $CORE_VERSION
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter $CORE_VERSION

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor $CORE_VERSION
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor $CORE_VERSION
  - gomod: github.com/elastic/opentelemetry-collector-components/processor/elasticinframetricsprocessor $ELASTICINFRAMETRICSPROCESSOR_VERSION
  - gomod: github.com/elastic/opentelemetry-collector-components/processor/elastictraceprocessor $ELASTICTRACEPROCESSOR_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/geoipprocessor $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor $CORE_VERSION
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor $CORE_VERSION
  - gomod: github.com/elastic/opentelemetry-collector-components/processor/lsmintervalprocessor $ELASTICTRACEPROCESSOR_VERSION

connectors:
  - gomod: github.com/elastic/opentelemetry-collector-components/connector/elasticapmconnector $ELASTICAPMCONNECTOR_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/routingconnector $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector $CORE_VERSION
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/otlpjsonconnector $CORE_VERSION

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider $PROVIDER_VERSION
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider $PROVIDER_VERSION
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider $PROVIDER_VERSION
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider $PROVIDER_VERSION
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider $PROVIDER_VERSION
  