apiVersion: v1
kind: Namespace
metadata:
  name: $NAMESPACE
  labels:
    name: $NAMESPACE
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-node-affinity
data:
  $NAMESPACE: |
    nodeSelectorTerms:
      - matchExpressions:
        - key: region
          operator: In
          values:
            - "$REGION"